### ISSUE TITLE
Map.new superfluous in `my constant %foo`

### ISSUE THREAD

**Issue by lizmat** [Kaiepi/ra-Acme-BaseCJK#1]
Not a micro-opt, just an observation.  Any `my constant %` will create a `Map`.

https://github.com/Kaiepi/ra-Acme-BaseCJK/blob/782136fbe215846f63fcfaafc0395d7a7f1aabea/lib/Acme/BaseCJK.rakumod#L17

**Comment by Kaiepi** [comment]
Thanks!
